//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProwatchWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProWatchEntities1 : DbContext
    {
        public ProWatchEntities1()
            : base("name=ProWatchEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<projectStatu> projectStatus { get; set; }
        public virtual DbSet<proUser> proUsers { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<UserProject> UserProjects { get; set; }
    }
}
