//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProwatchWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int reportID { get; set; }
        public string taskName { get; set; }
        public string reportDescription { get; set; }
        public string createdBy { get; set; }
        public int userID { get; set; }
        public Nullable<int> projectStatusID { get; set; }
        public Nullable<int> taskID { get; set; }
    
        public virtual projectStatu projectStatu { get; set; }
        public virtual proUser proUser { get; set; }
        public virtual task task { get; set; }
    }
}
