//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProwatchWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public task()
        {
            this.reports = new HashSet<report>();
        }
    
        public int taskID { get; set; }
        public string taskName { get; set; }
        public string observedBy { get; set; }
        public System.DateTime deadlineDate { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public string createdBy { get; set; }
        public int userID { get; set; }
        public Nullable<int> projectStatusID { get; set; }
        public string assignTo { get; set; }
        public Nullable<int> projectID { get; set; }
    
        public virtual project project { get; set; }
        public virtual projectStatu projectStatu { get; set; }
        public virtual proUser proUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report> reports { get; set; }
    }
}
