//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProwatchWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProject
    {
        public int upID { get; set; }
        public string createdBy { get; set; }
        public Nullable<int> projectID { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual project project { get; set; }
        public virtual proUser proUser { get; set; }
    }
}
